#!/bin/sh

[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

for command in mount umount sv pacman updatedb su shutdown poweroff reboot apt ; do
    alias $command="sudo $command"
done; unset command

alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -vI"
alias bc="bc -ql"
alias mkd="mkdir -pv"

alias ls="exa"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias ccat="highlight --out-format=ansi"
alias ip="ip -color=auto"

alias l="ls -a"
alias ll="ls -la"

alias y="yay"
alias ka="killall"
alias g="git"
alias e="nvim"
alias v="nvim"

alias za="zathura"
alias ok="okular"
alias nf="neofetch"

alias cl="clear"

alias t="tmux"
alias ta="tmux attach"
function tat() {
  echo $1
  tmux attach -t $1
}
alias td="tmux detach"

alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
